version: '3'

networks:
  web:
    external: true
  backend:

services:
  api:
    build: ./src/ApiServer
    depends_on:
    - database
    - mongo
    networks:
    - web
    - backend
    env_file: config.env
    expose:
    - "8779"

  database:
    image: mysql:5.7.29
    networks:
    - backend
    env_file: config.env

  database-client:
    build: ./src/MysqlClient
    depends_on:
    - database
    networks:
    - backend
    env_file: config.env

  database-manager:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - database
    networks:
    - web
    - backend
    env_file: config.env
    environment:
    - "PMA_HOST=database"
    expose:
    - "80"
    stdin_open: true
    tty: true

  mongo:
    image: mongo:4.2.3
    networks:
    - backend
    expose:
    - "27017"
    ports:
    - "8123:27017"
    env_file: config.env
