networks:
  web:
    external: true
  backend:

services:
  api:
    build: ./src/ApiServer
    networks:
    - web
    - backend
    env_file: config.env
    expose:
    - "8779"
    logging:
      driver: "local"
      options:
        max-size: "30m"
        max-file: "2"

  well-known:
    image: nginx:1.25-alpine
    networks:
    - web
    expose:
    - "80"
    volumes:
    - ./src/WellKnown/files:/usr/share/nginx/html:ro
    - ./src/WellKnown/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: "none"
