version: '3'

networks:
  web:
    external: true
  backend:

services:
  api:
    build: ./src/ApiServer
    depends_on:
    - mongo
    networks:
    - web
    - backend
    env_file: config.env
    expose:
    - "8779"
    logging:
      driver: "local"
      options:
        max-size: "30m"
        max-file: "2"
