networks:
  web:
    external: true
  backend:

services:
  api:
    networks:
    - web
    - backend
    env_file: config.env
    environment:
    - "GOOGLE_PROJECT_ID=wom-platform-308616"
    - "GOOGLE_APPLICATION_CREDENTIALS=/keys/wom-platform-308616.json"
    expose:
    - "8779"
    logging:
      driver: "local"
      options:
        max-size: "30m"
        max-file: "2"

  well-known:
    image: nginx:1.27-alpine
    networks:
    - web
    expose:
    - "80"
    volumes:
    - ./src/WellKnown/files:/usr/share/nginx/html:ro
    - ./src/WellKnown/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: "none"
