using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using MongoDB.Bson;
using MongoDB.Driver.GeoJsonObjectModel;
using WomPlatform.Connector;
using WomPlatform.Web.Api.DatabaseDocumentModels;
using WomPlatform.Web.Api.Service;

namespace WomPlatform.Web.Api.Controllers {

    /// <summary>
    /// Shared common base class for Registry controllers.
    /// </summary>
    [ApiController]
    [Produces("application/json")]
    public class BaseRegistryController : ControllerBase {

        protected readonly string SelfHostDomain;
        protected readonly string SelfLinkDomain;

        private readonly IServiceProvider _serviceProvider;

        public BaseRegistryController(
            IServiceProvider serviceProvider,
            ILogger<BaseRegistryController> logger
        ) {
            _serviceProvider = serviceProvider;
            Logger = logger;

            SelfHostDomain = Environment.GetEnvironmentVariable("SELF_HOST");
            SelfLinkDomain = Environment.GetEnvironmentVariable("LINK_HOST");
        }

        protected IConfiguration Configuration {
            get {
                return _serviceProvider.GetRequiredService<IConfiguration>();
            }
        }

        protected CryptoProvider Crypto {
            get {
                return _serviceProvider.GetRequiredService<CryptoProvider>();
            }
        }

        protected KeyManager KeyManager {
            get {
                return _serviceProvider.GetRequiredService<KeyManager>();
            }
        }

        protected ILogger<BaseRegistryController> Logger { get; }

        protected UserService UserService {
            get {
                return _serviceProvider.GetRequiredService<UserService>();
            }
        }

        protected (T, ActionResult) ExtractInputPayload<T>(string payload, int loggingKey) {
            try {
                return (Crypto.Decrypt<T>(payload, KeyManager.RegistryPrivateKey), null);
            }
            catch(Exception ex) {
                Logger.LogError(loggingKey, ex, "Failed to decrypt payload");
                return (default(T), ControllerExtensions.PayloadVerificationFailure(null));
            }
        }

        /// <summary>
        /// Checks whether a given voucher transfer password is acceptable.
        /// Null passwords are accepted as auto-generated.
        /// </summary>
        protected bool CheckTransferPassword(string password, bool acceptNullPasswords = true) {
            if(password == null && acceptNullPasswords) {
                // Null passwords will be autogenerated
                return true;
            }

            var confSection = Configuration.GetSection("PasswordSecurity");
            var minLength = Convert.ToInt32(confSection["MinimumLength"]);
            if(password.Length < minLength) {
                return false;
            }

            return true;
        }

        protected async Task<bool> VerifyUserIsAdminOfMerchant(Merchant merchant) {
            if(!User.GetUserId(out var loggedUserId)) {
                return false;
            }

            var userProfile = await UserService.GetUserById(loggedUserId);
            if(userProfile.Role == DatabaseDocumentModels.User.UserRole.Admin) {
                return true;
            }

            return !merchant.AdministratorIds.Contains(loggedUserId);
        }

    }

}
