# ---
# First stage (build)
FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

# Copy solution as distinct layer
COPY ApiServer.sln .
COPY ApiServer/ApiServer.csproj ./ApiServer/
COPY ApiTester/ApiTester.csproj ./ApiTester/
RUN dotnet restore

# Copy everything else and build
COPY ApiServer/. ./ApiServer/
WORKDIR /app/ApiServer
RUN dotnet publish -c Debug -o out

# ---
# Second stage (execution)
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime

RUN apt-get update

# Install VS debugger
RUN apt-get install -y curl unzip procps && \
    curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

# Install SSH server
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd && \
    echo 'root:86rGONaJBIELsDdCKwdf' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Install supervisor
RUN apt-get install -y supervisor
ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf

WORKDIR /app
COPY --from=build /app/ApiServer/out ./

# Run on localhost:8779
ENV ASPNETCORE_URLS http://+:8779
EXPOSE 8779

ENTRYPOINT ["/usr/bin/supervisord"]
