# Config override for deployment
version: '3'

volumes:
  wom_registry_database:
    external: true

services:
  api:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    volumes:
    - ../testkeys:/testkeys:ro
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=8779"
    - "traefik.frontend.rule=Host:dev.wom.social;PathPrefix:/api"
    - "traefik.frontend.entryPoints=http,https"

  database:
    volumes:
    - wom_registry_database:/var/lib/mysql:rw
