-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 12:05:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema VoucherPiattaforma
-- -----------------------------------------------------
USE `VoucherPiattaforma` ;

DROP TABLE `VoucherPiattaforma`.`Aims`;
DROP TABLE `VoucherPiattaforma`.`Contacts`;
DROP TABLE `VoucherPiattaforma`.`Sources`;
DROP TABLE `VoucherPiattaforma`.`POS`;
DROP TABLE `VoucherPiattaforma`.`PaymentRequests`;
DROP TABLE `VoucherPiattaforma`.`PaymentConfirmations`;
DROP TABLE `VoucherPiattaforma`.`GenerationRequests`;
DROP TABLE `VoucherPiattaforma`.`Vouchers`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
