-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 12:05:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Wom
-- -----------------------------------------------------
USE `Wom` ;

INSERT INTO `Wom`.`Contacts` (`Email`, `Name`, `Surname`) VALUES ('example@example.org', 'Sample', 'Sample');

INSERT INTO `Wom`.`Aims` (`Code`, `IconFile`, `Order`) VALUES ('1', 'aim-1', 3);
INSERT INTO `Wom`.`Aims` (`Code`, `IconFile`, `Order`) VALUES ('2', 'aim-2', 10);
INSERT INTO `Wom`.`Aims` (`Code`, `IconFile`, `Order`) VALUES ('11', 'aim-1-1', 0);
INSERT INTO `Wom`.`Aims` (`Code`, `IconFile`, `Order`) VALUES ('21', 'aim-2-1', 17);
INSERT INTO `Wom`.`Aims` (`Code`, `IconFile`, `Order`) VALUES ('22', 'aim-2-2', 2);
INSERT INTO `Wom`.`Aims` (`Code`, `IconFile`, `Order`) VALUES ('211', 'aim-2-1-1', 1);
INSERT INTO `Wom`.`Aims` (`Code`, `IconFile`, `Order`) VALUES ('3', 'aim-3', 1);

INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('1', 'en', 'Aim 1 English');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('1', 'it', 'Aim 1 Italiano');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('2', 'en', 'Aim 2 English');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('2', 'it', 'Aim 2 Italiano');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('11', 'en', 'Aim 1-1 English');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('11', 'it', 'Aim 1-1 Italiano');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('21', 'en', 'Aim 2-1 English');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('21', 'it', 'Aim 2-1 Italiano');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('22', 'en', 'Aim 2-2 English');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('22', 'it', 'Aim 2-2 Italiano');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('211', 'en', 'Aim 2-1-1 English');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('211', 'it', 'Aim 2-1-1 Italiano');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('3', 'en', 'Aim 3 English');
INSERT INTO `Wom`.`AimTitles` (`Code`, `LanguageCode`, `Title`) VALUES ('3', 'it', 'Aim 3 Italiano');

INSERT INTO `Wom`.`Sources` (`Name`, `PublicKey`, `CreationDate`, `URL`, `ContactID`) VALUES ('Sample source 1', '-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3ofbz4kneWa3Fv1PaYzu
acxNKC+Fokz9eHNMi6O5GK9GepY5O5aS++fhFGJ15HpwHHFv7hipSKFocTJ7+Fob
lBZwtIRPfvWBf+nWG1rqEjfVqVm7ZDrB70URrq049NdBEz3UXWTtAoynwq3kU19I
Nicr+ktYw7JYZpV7vgGrF7+tfDQfwP75ZbAFxbK4wK5dtmNuYGwOGTOJV/NQwjNd
nOu3tik2ef6znyFTpXtLa9dQjHa1hKqxWzxmoMaEOv8/Fbew017D0i5kq0cqnEnW
6sJaozfgBHRplgON3O5d12u2/sy2ome20lZzwWFQDtkHmVupFT3IhM3NyD+Dzl4e
MHvY2yr5FCecYuzB4CG585j23gxC5nNGnKrdWnQk+kEXvt4vZRYPLDXhLfmd959p
QMVIUw0hw4JqTJcjGGhrJzI7C7f4iRuPUoOXh3WW0j4WZBLEONaDzwI7Nm5IFFL1
QA2/o9EPna6iYq/WTnk+vgDr0AGfe2eu6siY5gJ0CDavd1ZMI3PybF9wuLsjzkWV
Cn/nedIE4Nid4toS738+flFMiXbbFyP0p0L2KQvH5O21569CWlOLBnEdDJ8xV1A+
21ILxbD3LDRela0W30fvikokJEZy1/eAZhtDNR3S6BNVpIEACGBml4rbJqZY8EuF
l/68yRYlTREY4L4mj9Vb6H0CAwEAAQ==
-----END PUBLIC KEY-----
', '2017-12-20', 'http://example.org', 1);

INSERT INTO `Wom`.`POS` (`Name`, `PublicKey`, `CreationDate`, `URL`) VALUES
('Sample POS 1', '-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0v/FRGQrynTC4nmDIwW5
bbEp3UdPrajdnIeCnV9d+KkQLL+/lkWmlZcIWyfEzpSVg/aC7DsABsxSruKVIWVo
L2QjDenbK1CzxU83XH7uR/RV79+uskuIzB0pRKdGq2ljeQlOufagIeOelLfLOApz
63AngpeOawYlZGZre9NL0I+QRPTlqDZjdd7X7AkyexpG4EOuIDG6/jFeQGWYoxtw
aVNuDd6KDZ5MF1d48tTEnH/rCZnNunfioEq9vPewwl5n0JmBSAEWvrxgU67t09hL
0SKGWH6njKHf2gw4N3ALQ0nqqeE5o9RjnHWYItjLrJutLX8AkCGnegO5eZWSz31Q
1S2V7N3cw0qrfEke95jwZw2UmmysqE8D9MyXsZfASU5piO5/Mz6Qfng7T6hkM2Df
mNWV4KVt6k5GYQzGXgNyxZMl6SCPd0zBMQyhPRPJxMhl0mu0odhjx/TN5/eDZP1d
dcQFJWz8l8Uqm0M8aiySTjKvEJrhAILWyLbz1kr3tgXDPcud+57FAdeURwcgIpOu
bZhrclevtmIcu3+ErIy711q4aoAXaR64MJ13vz7wbQek2GFy+omoITR0P+Rz46Rv
TezsXoL+zQvSpUm2o7dCeUGsWO6Q4blF/q4V3yJa9GHiHNJrNQtDFMa/ooOl3wKS
tsNv3HLk7sLtVU2GA0GrUgcCAwEAAQ==
-----END PUBLIC KEY-----
', '2019-02-08', 'http://example.org');
